version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8084:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
        depends_on:
            - php
        restart: always
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app:abhinav
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - mysql
        restart: always
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'abhinav'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'phpcms'
        volumes:
            - phpcms:/var/lib/mysql
        ports:
            - "33094:3306"
        restart: always
volumes:
    phpcms: {}
        
